fetching functions
Goldinium/math_magicians pull request #5
Opened 2023-09-22 12:12 UTC by Goldinium

- Used an external API: [API Ninjas](https://api-ninjas.com/api/quotes)
- Created a new component for displaying a quote
- Fetched data inside of a new component
- Showed a `loading` state
- Showed an `error` state
- Imported the new component into the main component (next to the Calculator)
- Practiced what I have learned until now: used `useEffect` and `props`.

Thank you

2023-09-22 12:26 UTC, Efiamotu-1 requested changes
Hi @Goldinium >, 

![](https://user-images.githubusercontent.com/89055502/221963929-dc172827-5c2c-411b-bf4d-923659f626e1.gif) 

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-22 12:26 UTC, Efiamotu-1 commented on src/App.js
- [ ] Also i noticed that when the page loads it generates two quotes that are being displayed on the screen, this is happening as a result of the `<React.Strictmode></React.Strictmode>` which wraps your app component in your index.js file, if you remove it only one quote would be displayed at the start of the webpage. see this [link](https://legacy.reactjs.org/docs/strict-mode.html) to learn more about this

2023-09-22 12:26 UTC, Efiamotu-1 commented on src/App.js
- [ ] In your readme file, you have a broken link in your `Contributing` section, the link to your project's github issue is currently throwing up a 404 error page, Please kindly provide the appropriate link to your issues page as it is unprofessional to leave broken links in your readme file :+1: :sparkles: 
![re](https://github.com/Goldinium/math_magicians/assets/89055502/d09ffb97-a44c-4ebf-b77d-839ab08e2a54)

2023-09-22 12:33 UTC, Goldinium commented on src/App.js
fixed

2023-09-22 12:34 UTC, Goldinium commented on src/App.js
I'm not sure about that, on my side it's fetching and showing only one quote.

2023-09-22 12:54 UTC, Alusp requested changes
Hi @Goldinium, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![close](https://media.giphy.com/media/nJKDTpuxnZE7fb6Z1b/giphy.gif)

 ## Highlights

- [x] Linters set-up ✔️
- [x] Commit messages descrptive ✔️
- [x] Professional Github Flow used ✔️
- [x] Professional PR Summary Flow used ✔️
- [x] UI Closer to the given design :heavy_check_mark:  
- [ ] Connect to an API within a functional component. :heavy_check_mark:  


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Alusp in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-22 12:54 UTC, Alusp commented on src/App.js
- [ ] Very good job in implementing the changes requested by the previous reviewer, :clap: , However, as he mentioned earlier, Please remove `<React.Strictmode></React.Strictmode>` which wraps your app component in your `index.js` file and see the magic. :slightly_smiling_face: , because currently, your App throws two quotes for each refresh, you will only notice it if you look closely or if you are on a slow network. :slightly_smiling_face:

2023-09-22 13:01 UTC, Goldinium commented on src/App.js
I just talked with him, there is only one quote loading, even with using the `<React.Strictmode>` tag, please verify again and let me know.

2023-09-22 13:04 UTC, Goldinium commented on src/App.js
Okay i removed it anyway, let's see now..

2023-09-22 13:08 UTC, Efiamotu-1 approved these changes
Hi @Goldinium , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)

## Highlights :dart: 
* Correct GitHub flow or Gitflow :heavy_check_mark: 
* Good commit messages :heavy_check_mark: 
* All linters passing :heavy_check_mark: 
* Good PR summary :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-22 13:10 UTC, merged

2023-09-22 13:52 UTC, Alusp commented on src/App.js
@Goldinium, Actually, it was showing on my end and its good remove it. 🙂

2023-09-22 14:49 UTC, Goldinium commented on src/App.js
@Alusp  I would like to see a screenshot from your side showing the issue.

2023-09-22 21:43 UTC, Alusp commented on src/App.js
@Alusp, Unfortunately, the Linux version am using does not support screen video recording, however, you can reach me on oom or huddle, so I can show you in real time. :slightly_smiling_face:

2023-09-23 06:14 UTC, Goldinium commented on src/App.js
@Alusp  i sent you a message on slack

2023-09-23 12:25 UTC, Alusp commented on src/App.js
Alright @Goldinium, Please indicate the topic of discussion so can be able to know its you, :slightly_smiling_face: , I get a lot of DMs. :smiley: